#![no_std]
use core::panic::PanicInfo;
#[panic_handler] fn p(_: &PanicInfo) -> ! { loop {} }
#[no_mangle] pub extern "C" fn wl_display_dispatch_pending() -> usize { 0 }
#[no_mangle] pub extern "C" fn XCreateIC() -> usize { 0 }
#[no_mangle] pub extern "C" fn XDrawString() -> usize { 0 }
#[no_mangle] pub extern "C" fn XkbFreeKeyboard() -> usize { 0 }
#[no_mangle] pub extern "C" fn XQueryExtension() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_get_chmap() -> usize { 0 }
#[no_mangle] pub extern "C" fn XLookupKeysym() -> usize { 0 }
#[no_mangle] pub extern "C" fn _XReply() -> usize { 0 }
#[no_mangle] pub extern "C" fn XRRFreeScreenConfigInfo() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_device_name_get_hint() -> usize { 0 }
#[no_mangle] pub extern "C" fn XdbeDeallocateBackBufferName() -> usize { 0 }
#[no_mangle] pub extern "C" fn XineramaQueryScreens() -> usize { 0 }
#[no_mangle] pub extern "C" fn XRRGetOutputProperty() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_stream_connect_playback() -> usize { 0 }
#[no_mangle] pub extern "C" fn XCreateFontCursor() -> usize { 0 }
#[no_mangle] pub extern "C" fn XFree() -> usize { 0 }
#[no_mangle] pub extern "C" fn XdbeQueryExtension() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_proxy_add_listener() -> usize { 0 }
#[no_mangle] pub extern "C" fn XkbSetDetectableAutoRepeat() -> usize { 0 }
#[no_mangle] pub extern "C" fn XRRFreeScreenResources() -> usize { 0 }
#[no_mangle] pub extern "C" fn XMoveWindow() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_hw_params_any() -> usize { 0 }
#[no_mangle] pub extern "C" fn XFreeCursor() -> usize { 0 }
#[no_mangle] pub extern "C" fn XRRSetCrtcConfig() -> usize { 0 }
#[no_mangle] pub extern "C" fn XScreenSaverQueryVersion() -> usize { 0 }
#[no_mangle] pub extern "C" fn XkbGetMap() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_close() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_stream_disconnect() -> usize { 0 }
#[no_mangle] pub extern "C" fn XRRListOutputProperties() -> usize { 0 }
#[no_mangle] pub extern "C" fn XIFreeDeviceInfo() -> usize { 0 }
#[no_mangle] pub extern "C" fn XRRFreeCrtcInfo() -> usize { 0 }
#[no_mangle] pub extern "C" fn XdbeAllocateBackBufferName() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_context_get_source_info_by_index() -> usize { 0 }
#[no_mangle] pub extern "C" fn XClearWindow() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_get_library_version() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_context_get_sink_info_list() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_proxy_destroy() -> usize { 0 }
#[no_mangle] pub extern "C" fn XdbeFreeVisualInfo() -> usize { 0 }
#[no_mangle] pub extern "C" fn XListPixmapFormats() -> usize { 0 }
#[no_mangle] pub extern "C" fn XF86VidModeLockModeSwitch() -> usize { 0 }
#[no_mangle] pub extern "C" fn XRRGetOutputInfo() -> usize { 0 }
#[no_mangle] pub extern "C" fn XRRSetScreenConfigAndRate() -> usize { 0 }
#[no_mangle] pub extern "C" fn XESetEventToWire() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_display_connect_to_fd() -> usize { 0 }
#[no_mangle] pub extern "C" fn XStoreName() -> usize { 0 }
#[no_mangle] pub extern "C" fn XAllocClassHint() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_mainloop_new() -> usize { 0 }
#[no_mangle] pub extern "C" fn XRefreshKeyboardMapping() -> usize { 0 }
#[no_mangle] pub extern "C" fn XGrabServer() -> usize { 0 }
#[no_mangle] pub extern "C" fn XGetWMNormalHints() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_list_insert_list() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_context_get_source_info_list() -> usize { 0 }
#[no_mangle] pub extern "C" fn XdbeBeginIdiom() -> usize { 0 }
#[no_mangle] pub extern "C" fn XAutoRepeatOff() -> usize { 0 }
#[no_mangle] pub extern "C" fn XLookupString() -> usize { 0 }
#[no_mangle] pub extern "C" fn _XFlushGCCache() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_display_disconnect() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_list_init() -> usize { 0 }
#[no_mangle] pub extern "C" fn XCreateImage() -> usize { 0 }
#[no_mangle] pub extern "C" fn XFreeFont() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_sw_params_sizeof() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_hw_params_set_period_size_near() -> usize { 0 }
#[no_mangle] pub extern "C" fn XShmCreatePixmap() -> usize { 0 }
#[no_mangle] pub extern "C" fn XRaiseWindow() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_stream_readable_size() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_proxy_create() -> usize { 0 }
#[no_mangle] pub extern "C" fn XConvertSelection() -> usize { 0 }
#[no_mangle] pub extern "C" fn xkb_context_unref() -> usize { 0 }
#[no_mangle] pub extern "C" fn XUngrabPointer() -> usize { 0 }
#[no_mangle] pub extern "C" fn XGetWindowProperty() -> usize { 0 }
#[no_mangle] pub extern "C" fn XScreenSaverSuspend() -> usize { 0 }
#[no_mangle] pub extern "C" fn XFreeModifiermap() -> usize { 0 }
#[no_mangle] pub extern "C" fn XMissingExtension() -> usize { 0 }
#[no_mangle] pub extern "C" fn XineramaQueryExtension() -> usize { 0 }
#[no_mangle] pub extern "C" fn XkbFreeClientMap() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_cursor_theme_get_cursor() -> usize { 0 }
#[no_mangle] pub extern "C" fn XMatchVisualInfo() -> usize { 0 }
#[no_mangle] pub extern "C" fn XSetWMNormalHints() -> usize { 0 }
#[no_mangle] pub extern "C" fn XGrabPointer() -> usize { 0 }
#[no_mangle] pub extern "C" fn xkb_keymap_unref() -> usize { 0 }
#[no_mangle] pub extern "C" fn XRRQueryVersion() -> usize { 0 }
#[no_mangle] pub extern "C" fn _XFlush() -> usize { 0 }
#[no_mangle] pub extern "C" fn XCreateWindow() -> usize { 0 }
#[no_mangle] pub extern "C" fn Xutf8ResetIC() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_hw_params() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_sw_params_set_avail_min() -> usize { 0 }
#[no_mangle] pub extern "C" fn XIconifyWindow() -> usize { 0 }
#[no_mangle] pub extern "C" fn XkbKeycodeToKeysym() -> usize { 0 }
#[no_mangle] pub extern "C" fn XTranslateCoordinates() -> usize { 0 }
#[no_mangle] pub extern "C" fn XF86VidModeQueryVersion() -> usize { 0 }
#[no_mangle] pub extern "C" fn XCreateColormap() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_hw_params_sizeof() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_cursor_frame() -> usize { 0 }
#[no_mangle] pub extern "C" fn XF86VidModeGetModeLine() -> usize { 0 }
#[no_mangle] pub extern "C" fn XISelectEvents() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_list_remove() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_proxy_set_queue() -> usize { 0 }
#[no_mangle] pub extern "C" fn XAutoRepeatOn() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_operation_get_state() -> usize { 0 }
#[no_mangle] pub extern "C" fn XQueryKeymap() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_log_set_handler_client() -> usize { 0 }
#[no_mangle] pub extern "C" fn _XEatData() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_stream_write() -> usize { 0 }
#[no_mangle] pub extern "C" fn XRRConfigRates() -> usize { 0 }
#[no_mangle] pub extern "C" fn XOpenDisplay() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_display_get_error() -> usize { 0 }
#[no_mangle] pub extern "C" fn XkbQueryExtension() -> usize { 0 }
#[no_mangle] pub extern "C" fn Xutf8DrawString() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_context_connect() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_open() -> usize { 0 }
#[no_mangle] pub extern "C" fn XSetWMProperties() -> usize { 0 }
#[no_mangle] pub extern "C" fn XFreeFontSet() -> usize { 0 }
#[no_mangle] pub extern "C" fn XGetEventData() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_mainloop_iterate() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_context_disconnect() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_context_get_state() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_display_dispatch() -> usize { 0 }
#[no_mangle] pub extern "C" fn XAllocWMHints() -> usize { 0 }
#[no_mangle] pub extern "C" fn XFilterEvent() -> usize { 0 }
#[no_mangle] pub extern "C" fn XIGetSelectedEvents() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_proxy_get_class() -> usize { 0 }
#[no_mangle] pub extern "C" fn XUnloadFont() -> usize { 0 }
#[no_mangle] pub extern "C" fn XRRGetScreenSizeRange() -> usize { 0 }
#[no_mangle] pub extern "C" fn XDisplayKeycodes() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_list_length() -> usize { 0 }
#[no_mangle] pub extern "C" fn XDeleteProperty() -> usize { 0 }
#[no_mangle] pub extern "C" fn XRRGetOutputPrimary() -> usize { 0 }
#[no_mangle] pub extern "C" fn XdbeEndIdiom() -> usize { 0 }
#[no_mangle] pub extern "C" fn XSynchronize() -> usize { 0 }
#[no_mangle] pub extern "C" fn XDestroyWindow() -> usize { 0 }
#[no_mangle] pub extern "C" fn XCloseDisplay() -> usize { 0 }
#[no_mangle] pub extern "C" fn Xutf8LookupString() -> usize { 0 }
#[no_mangle] pub extern "C" fn XF86VidModeGetAllModeLines() -> usize { 0 }
#[no_mangle] pub extern "C" fn XextRemoveDisplay() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_sw_params() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_recover() -> usize { 0 }
#[no_mangle] pub extern "C" fn XGetErrorText() -> usize { 0 }
#[no_mangle] pub extern "C" fn XcursorImageCreate() -> usize { 0 }
#[no_mangle] pub extern "C" fn XSetForeground() -> usize { 0 }
#[no_mangle] pub extern "C" fn XFillRectangle() -> usize { 0 }
#[no_mangle] pub extern "C" fn XShmCreateImage() -> usize { 0 }
#[no_mangle] pub extern "C" fn XUnsetICFocus() -> usize { 0 }
#[no_mangle] pub extern "C" fn XRRConfigCurrentRate() -> usize { 0 }
#[no_mangle] pub extern "C" fn XF86VidModeQueryExtension() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_context_unref() -> usize { 0 }
#[no_mangle] pub extern "C" fn XGetErrorDatabaseText() -> usize { 0 }
#[no_mangle] pub extern "C" fn XCreateFontSet() -> usize { 0 }
#[no_mangle] pub extern "C" fn XSetTransientForHint() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_mainloop_get_api() -> usize { 0 }
#[no_mangle] pub extern "C" fn XF86VidModeGetViewPort() -> usize { 0 }
#[no_mangle] pub extern "C" fn xkb_state_unref() -> usize { 0 }
#[no_mangle] pub extern "C" fn XdbeSwapBuffers() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_writei() -> usize { 0 }
#[no_mangle] pub extern "C" fn XCreatePixmapCursor() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_context_set_subscribe_callback() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_chmap_print() -> usize { 0 }
#[no_mangle] pub extern "C" fn XextCreateExtension() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_device_name_hint() -> usize { 0 }
#[no_mangle] pub extern "C" fn xkb_state_key_get_syms() -> usize { 0 }
#[no_mangle] pub extern "C" fn XIQueryDevice() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_stream_unref() -> usize { 0 }
#[no_mangle] pub extern "C" fn XFreeGC() -> usize { 0 }
#[no_mangle] pub extern "C" fn XUngrabServer() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_stream_get_state() -> usize { 0 }
#[no_mangle] pub extern "C" fn XDisplayName() -> usize { 0 }
#[no_mangle] pub extern "C" fn XcursorImageLoadCursor() -> usize { 0 }
#[no_mangle] pub extern "C" fn XDrawRectangle() -> usize { 0 }
#[no_mangle] pub extern "C" fn XkbGetState() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_wait() -> usize { 0 }
#[no_mangle] pub extern "C" fn XRRGetScreenResources() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_stream_new() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_readi() -> usize { 0 }
#[no_mangle] pub extern "C" fn XNextEvent() -> usize { 0 }
#[no_mangle] pub extern "C" fn XWindowEvent() -> usize { 0 }
#[no_mangle] pub extern "C" fn XResetScreenSaver() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_strerror() -> usize { 0 }
#[no_mangle] pub extern "C" fn _XRead() -> usize { 0 }
#[no_mangle] pub extern "C" fn XSetWMProtocols() -> usize { 0 }
#[no_mangle] pub extern "C" fn Xutf8TextListToTextProperty() -> usize { 0 }
#[no_mangle] pub extern "C" fn XSetTextProperty() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_context_new() -> usize { 0 }
#[no_mangle] pub extern "C" fn xkb_state_new() -> usize { 0 }
#[no_mangle] pub extern "C" fn _XSetLastRequestRead() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_mainloop_free() -> usize { 0 }
#[no_mangle] pub extern "C" fn XIQueryVersion() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_list_insert() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_mainloop_quit() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_proxy_set_user_data() -> usize { 0 }
#[no_mangle] pub extern "C" fn XKeysymToString() -> usize { 0 }
#[no_mangle] pub extern "C" fn XResizeWindow() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_reset() -> usize { 0 }
#[no_mangle] pub extern "C" fn xkb_context_new() -> usize { 0 }
#[no_mangle] pub extern "C" fn XRRSetScreenSize() -> usize { 0 }
#[no_mangle] pub extern "C" fn XSetIOErrorHandler() -> usize { 0 }
#[no_mangle] pub extern "C" fn XChangePointerControl() -> usize { 0 }
#[no_mangle] pub extern "C" fn XIfEvent() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_channel_map_init_auto() -> usize { 0 }
#[no_mangle] pub extern "C" fn XUngrabKeyboard() -> usize { 0 }
#[no_mangle] pub extern "C" fn XGetInputFocus() -> usize { 0 }
#[no_mangle] pub extern "C" fn XCreateBitmapFromData() -> usize { 0 }
#[no_mangle] pub extern "C" fn XGetWMHints() -> usize { 0 }
#[no_mangle] pub extern "C" fn XextDestroyExtension() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_hw_params_set_periods_min() -> usize { 0 }
#[no_mangle] pub extern "C" fn XDisplayString() -> usize { 0 }
#[no_mangle] pub extern "C" fn XShmQueryExtension() -> usize { 0 }
#[no_mangle] pub extern "C" fn XSetWindowBackground() -> usize { 0 }
#[no_mangle] pub extern "C" fn XCreateGC() -> usize { 0 }
#[no_mangle] pub extern "C" fn XSelectInput() -> usize { 0 }
#[no_mangle] pub extern "C" fn XSetInputFocus() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_mainloop_run() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_operation_unref() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_display_connect() -> usize { 0 }
#[no_mangle] pub extern "C" fn XDestroyIC() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_proxy_marshal() -> usize { 0 }
#[no_mangle] pub extern "C" fn XFlush() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_hw_params_get_buffer_size() -> usize { 0 }
#[no_mangle] pub extern "C" fn XSync() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_display_dispatch_queue_pending() -> usize { 0 }
#[no_mangle] pub extern "C" fn XF86VidModeSwitchToMode() -> usize { 0 }
#[no_mangle] pub extern "C" fn XSetSelectionOwner() -> usize { 0 }
#[no_mangle] pub extern "C" fn XStoreColors() -> usize { 0 }
#[no_mangle] pub extern "C" fn XSendEvent() -> usize { 0 }
#[no_mangle] pub extern "C" fn XSetICFocus() -> usize { 0 }
#[no_mangle] pub extern "C" fn XWarpPointer() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_egl_window_destroy() -> usize { 0 }
#[no_mangle] pub extern "C" fn XWithdrawWindow() -> usize { 0 }
#[no_mangle] pub extern "C" fn XGetAtomName() -> usize { 0 }
#[no_mangle] pub extern "C" fn XRRConfigSizes() -> usize { 0 }
#[no_mangle] pub extern "C" fn Xutf8TextExtents() -> usize { 0 }
#[no_mangle] pub extern "C" fn XdbeGetVisualInfo() -> usize { 0 }
#[no_mangle] pub extern "C" fn XPutImage() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_egl_window_create() -> usize { 0 }
#[no_mangle] pub extern "C" fn XFreeEventData() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_list_empty() -> usize { 0 }
#[no_mangle] pub extern "C" fn XGetICValues() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_hw_params_set_rate_near() -> usize { 0 }
#[no_mangle] pub extern "C" fn XShmAttach() -> usize { 0 }
#[no_mangle] pub extern "C" fn XCheckIfEvent() -> usize { 0 }
#[no_mangle] pub extern "C" fn XPeekEvent() -> usize { 0 }
#[no_mangle] pub extern "C" fn XLoadQueryFont() -> usize { 0 }
#[no_mangle] pub extern "C" fn XTextExtents() -> usize { 0 }
#[no_mangle] pub extern "C" fn xkb_state_update_mask() -> usize { 0 }
#[no_mangle] pub extern "C" fn XkbGetUpdatedMap() -> usize { 0 }
#[no_mangle] pub extern "C" fn XShapeCombineMask() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_display_dispatch_queue() -> usize { 0 }
#[no_mangle] pub extern "C" fn XInitThreads() -> usize { 0 }
#[no_mangle] pub extern "C" fn XOpenIM() -> usize { 0 }
#[no_mangle] pub extern "C" fn XKeycodeToKeysym() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_hw_params_set_access() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_display_flush() -> usize { 0 }
#[no_mangle] pub extern "C" fn XRRConfigCurrentConfiguration() -> usize { 0 }
#[no_mangle] pub extern "C" fn XFreeStringList() -> usize { 0 }
#[no_mangle] pub extern "C" fn XextFindDisplay() -> usize { 0 }
#[no_mangle] pub extern "C" fn XInstallColormap() -> usize { 0 }
#[no_mangle] pub extern "C" fn XineramaIsActive() -> usize { 0 }
#[no_mangle] pub extern "C" fn _XSend() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_proxy_get_version() -> usize { 0 }
#[no_mangle] pub extern "C" fn XDefineCursor() -> usize { 0 }
#[no_mangle] pub extern "C" fn XRRQueryOutputProperty() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_hw_params_set_channels() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_hw_params_copy() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_stream_peek() -> usize { 0 }
#[no_mangle] pub extern "C" fn XGetModifierMapping() -> usize { 0 }
#[no_mangle] pub extern "C" fn XdbeGetBackBufferAttributes() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_cursor_theme_load() -> usize { 0 }
#[no_mangle] pub extern "C" fn XInternAtom() -> usize { 0 }
#[no_mangle] pub extern "C" fn XGrabKeyboard() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_nonblock() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_hw_params_set_periods_first() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_egl_window_get_attached_size() -> usize { 0 }
#[no_mangle] pub extern "C" fn XQueryPointer() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_stream_connect_record() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_proxy_marshal_constructor() -> usize { 0 }
#[no_mangle] pub extern "C" fn XUndefineCursor() -> usize { 0 }
#[no_mangle] pub extern "C" fn XRRGetCrtcInfo() -> usize { 0 }
#[no_mangle] pub extern "C" fn XGetVisualInfo() -> usize { 0 }
#[no_mangle] pub extern "C" fn XVisualIDFromVisual() -> usize { 0 }
#[no_mangle] pub extern "C" fn XKeysymToKeycode() -> usize { 0 }
#[no_mangle] pub extern "C" fn XScreenSaverQueryExtension() -> usize { 0 }
#[no_mangle] pub extern "C" fn XSetLocaleModifiers() -> usize { 0 }
#[no_mangle] pub extern "C" fn XextAddDisplay() -> usize { 0 }
#[no_mangle] pub extern "C" fn XGetWindowAttributes() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_proxy_get_id() -> usize { 0 }
#[no_mangle] pub extern "C" fn XRRGetScreenInfo() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_context_get_sink_info_by_index() -> usize { 0 }
#[no_mangle] pub extern "C" fn XChangeProperty() -> usize { 0 }
#[no_mangle] pub extern "C" fn XAllocSizeHints() -> usize { 0 }
#[no_mangle] pub extern "C" fn XShmPutImage() -> usize { 0 }
#[no_mangle] pub extern "C" fn XSetErrorHandler() -> usize { 0 }
#[no_mangle] pub extern "C" fn XFreePixmap() -> usize { 0 }
#[no_mangle] pub extern "C" fn XESetWireToEvent() -> usize { 0 }
#[no_mangle] pub extern "C" fn XGetKeyboardControl() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_stream_drop() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_stream_writable_size() -> usize { 0 }
#[no_mangle] pub extern "C" fn XGetPointerControl() -> usize { 0 }
#[no_mangle] pub extern "C" fn XcursorImageDestroy() -> usize { 0 }
#[no_mangle] pub extern "C" fn XStringListToTextProperty() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_display_get_fd() -> usize { 0 }
#[no_mangle] pub extern "C" fn XReparentWindow() -> usize { 0 }
#[no_mangle] pub extern "C" fn XMapRaised() -> usize { 0 }
#[no_mangle] pub extern "C" fn pa_context_subscribe() -> usize { 0 }
#[no_mangle] pub extern "C" fn XUninstallColormap() -> usize { 0 }
#[no_mangle] pub extern "C" fn XCloseIM() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_egl_window_resize() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_proxy_get_user_data() -> usize { 0 }
#[no_mangle] pub extern "C" fn _XReadPad() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_proxy_marshal_constructor_versioned() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_display_create_queue() -> usize { 0 }
#[no_mangle] pub extern "C" fn xkb_keysym_to_utf8() -> usize { 0 }
#[no_mangle] pub extern "C" fn XQueryTree() -> usize { 0 }
#[no_mangle] pub extern "C" fn XShmDetach() -> usize { 0 }
#[no_mangle] pub extern "C" fn XGetSelectionOwner() -> usize { 0 }
#[no_mangle] pub extern "C" fn XEventsQueued() -> usize { 0 }
#[no_mangle] pub extern "C" fn XRRFreeOutputInfo() -> usize { 0 }
#[no_mangle] pub extern "C" fn xkb_keymap_new_from_string() -> usize { 0 }
#[no_mangle] pub extern "C" fn XRRGetScreenResourcesCurrent() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_hw_params_set_format() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_hw_params_get_channels() -> usize { 0 }
#[no_mangle] pub extern "C" fn XineramaQueryVersion() -> usize { 0 }
#[no_mangle] pub extern "C" fn XPending() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_cursor_image_get_buffer() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_sw_params_current() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_device_name_free_hint() -> usize { 0 }
#[no_mangle] pub extern "C" fn snd_pcm_sw_params_set_start_threshold() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_display_roundtrip() -> usize { 0 }
#[no_mangle] pub extern "C" fn wl_cursor_theme_destroy() -> usize { 0 }
