[build]
target = "aarch64-unknown-linux-musl"
[target.aarch64-unknown-linux-musl]
linker = "rust-lld"
rustflags = ["-C","linker-flavor=ld.lld","-C","target-feature=-crt-static","-C","relocation-model=pic","-C","link-arg=-nostdlib","-C","link-arg=-Lstub","-C","link-arg=--dynamic-linker=/lib/ld-linux-aarch64.so.1","-C","link-arg=--allow-shlib-undefined","-C","force-unwind-tables=no"]
